name: Update RSS Feed

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Post title"
        required: true
      link:
        description: "Canonical URL"
        required: true
      description:
        description: "Short description"
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show repo tree (debug)
        run: |
          echo "PWD=$(pwd)"
          git rev-parse --show-toplevel
          ls -la
          echo "--- scripts dir ---"
          ls -la scripts || true

      - name: Update feed.xml
        run: |
          python -V
          python ./scripts/add_item.py \
            "${{ github.event.inputs.title }}" \
            "${{ github.event.inputs.link }}" \
            "${{ github.event.inputs.description }}"

      - name: Commit & push if changed
        run: |
          git config user.name "Riggs Bot"
          git config user.email "actions@users.noreply.github.com"
          if ! git diff --quiet; then
            git add feed.xml
            git commit -m "Add item: ${{ github.event.inputs.title }}"
            git push
          else
            echo "No changes to commit."
          fi
