name: Update RSS Feed

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Post title"
        required: true
      link:
        description: "Canonical URL"
        required: true
      description:
        description: "Short description"
        required: true
  repository_dispatch:
    types: [riggs_new_post]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows the action to push feed.xml changes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prepare inputs
        id: prep
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TITLE=${{ github.event.inputs.title }}" >> $GITHUB_OUTPUT
            echo "LINK=${{ github.event.inputs.link }}" >> $GITHUB_OUTPUT
            echo "DESC=${{ github.event.inputs.description }}" >> $GITHUB_OUTPUT
          else
            echo "TITLE=${{ github.event.client_payload.title }}" >> $GITHUB_OUTPUT
            echo "LINK=${{ github.event.client_payload.link }}" >> $GITHUB_OUTPUT
            echo "DESC=${{ github.event.client_payload.description }}" >> $GITHUB_OUTPUT
            echo "GUID=${{ github.event.client_payload.guid }}" >> $GITHUB_OUTPUT
          fi

      - name: Update feed.xml
        run: |
          python scripts/add_item.py \
            "${{ steps.prep.outputs.TITLE }}" \
            "${{ steps.prep.outputs.LINK }}" \
            "${{ steps.prep.outputs.DESC }}" \
            "${{ steps.prep.outputs.GUID }}"

      - name: Commit & push if changed
        run: |
          git config user.name "Riggs Bot"
          git config user.email "actions@users.noreply.github.com"
          if ! git diff --quiet; then
            git add feed.xml
            git commit -m "Add item: ${{ steps.prep.outputs.TITLE }}"
            git push
          else
            echo "No changes to commit."
          fi
